# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/GridUI/GridUI.ui'
#
# Created: Thu Jun 30 20:12:08 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BCARM(object):
    def setupUi(self, BCARM):
        BCARM.setObjectName(_fromUtf8("BCARM"))
        BCARM.resize(800, 480)
        BCARM.setStyleSheet(_fromUtf8("background: rgb(0, 0, 0)"))
        self.centralWidget = QtGui.QWidget(BCARM)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.B = QtGui.QLabel(self.centralWidget)
        self.B.setGeometry(QtCore.QRect(250, 0, 120, 120))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.B.setFont(font)
        self.B.setStyleSheet(_fromUtf8("color: rgb(61, 61, 61)"))
        self.B.setAlignment(QtCore.Qt.AlignCenter)
        self.B.setObjectName(_fromUtf8("B"))
        self.A = QtGui.QLabel(self.centralWidget)
        self.A.setGeometry(QtCore.QRect(0, 0, 120, 120))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.A.setFont(font)
        self.A.setStyleSheet(_fromUtf8("color: rgb(61, 61, 61)"))
        self.A.setAlignment(QtCore.Qt.AlignCenter)
        self.A.setObjectName(_fromUtf8("A"))
        self.C = QtGui.QLabel(self.centralWidget)
        self.C.setGeometry(QtCore.QRect(500, 0, 120, 120))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.C.setFont(font)
        self.C.setStyleSheet(_fromUtf8("color: rgb(61, 61, 61)"))
        self.C.setAlignment(QtCore.Qt.AlignCenter)
        self.C.setObjectName(_fromUtf8("C"))
        self.E = QtGui.QLabel(self.centralWidget)
        self.E.setGeometry(QtCore.QRect(250, 180, 120, 120))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.E.setFont(font)
        self.E.setStyleSheet(_fromUtf8("color: rgb(61, 61, 61)"))
        self.E.setAlignment(QtCore.Qt.AlignCenter)
        self.E.setObjectName(_fromUtf8("E"))
        self.D = QtGui.QLabel(self.centralWidget)
        self.D.setGeometry(QtCore.QRect(0, 180, 120, 120))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.D.setFont(font)
        self.D.setStyleSheet(_fromUtf8("color: rgb(61, 61, 61)"))
        self.D.setAlignment(QtCore.Qt.AlignCenter)
        self.D.setObjectName(_fromUtf8("D"))
        self.F = QtGui.QLabel(self.centralWidget)
        self.F.setGeometry(QtCore.QRect(500, 180, 120, 120))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.F.setFont(font)
        self.F.setStyleSheet(_fromUtf8("color: rgb(61, 61, 61)"))
        self.F.setAlignment(QtCore.Qt.AlignCenter)
        self.F.setObjectName(_fromUtf8("F"))
        self.H = QtGui.QLabel(self.centralWidget)
        self.H.setGeometry(QtCore.QRect(250, 360, 120, 120))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.H.setFont(font)
        self.H.setStyleSheet(_fromUtf8("color: rgb(61, 61, 61)"))
        self.H.setAlignment(QtCore.Qt.AlignCenter)
        self.H.setObjectName(_fromUtf8("H"))
        self.G = QtGui.QLabel(self.centralWidget)
        self.G.setGeometry(QtCore.QRect(0, 360, 120, 120))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.G.setFont(font)
        self.G.setStyleSheet(_fromUtf8("color: rgb(61, 61, 61)"))
        self.G.setAlignment(QtCore.Qt.AlignCenter)
        self.G.setObjectName(_fromUtf8("G"))
        self.I = QtGui.QLabel(self.centralWidget)
        self.I.setGeometry(QtCore.QRect(500, 360, 120, 120))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.I.setFont(font)
        self.I.setStyleSheet(_fromUtf8("color: rgb(61, 61, 61)"))
        self.I.setAlignment(QtCore.Qt.AlignCenter)
        self.I.setObjectName(_fromUtf8("I"))
        self.objA = QtGui.QLabel(self.centralWidget)
        self.objA.setGeometry(QtCore.QRect(700, 10, 80, 50))
        self.objA.setText(_fromUtf8(""))
        self.objA.setObjectName(_fromUtf8("objA"))
        self.lbl_objA = QtGui.QLabel(self.centralWidget)
        self.lbl_objA.setEnabled(True)
        self.lbl_objA.setGeometry(QtCore.QRect(725, 65, 30, 25))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_objA.setFont(font)
        self.lbl_objA.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255)\n"
"\n"
""))
        self.lbl_objA.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_objA.setObjectName(_fromUtf8("lbl_objA"))
        self.lbl_objB = QtGui.QLabel(self.centralWidget)
        self.lbl_objB.setGeometry(QtCore.QRect(725, 160, 30, 25))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_objB.setFont(font)
        self.lbl_objB.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255)\n"
"\n"
""))
        self.lbl_objB.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_objB.setObjectName(_fromUtf8("lbl_objB"))
        self.objB = QtGui.QLabel(self.centralWidget)
        self.objB.setGeometry(QtCore.QRect(700, 100, 80, 50))
        self.objB.setText(_fromUtf8(""))
        self.objB.setObjectName(_fromUtf8("objB"))
        self.lbl_objC = QtGui.QLabel(self.centralWidget)
        self.lbl_objC.setGeometry(QtCore.QRect(725, 260, 30, 25))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_objC.setFont(font)
        self.lbl_objC.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255)\n"
"\n"
""))
        self.lbl_objC.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_objC.setObjectName(_fromUtf8("lbl_objC"))
        self.objC = QtGui.QLabel(self.centralWidget)
        self.objC.setGeometry(QtCore.QRect(700, 200, 80, 50))
        self.objC.setText(_fromUtf8(""))
        self.objC.setObjectName(_fromUtf8("objC"))
        self.lbl_objD = QtGui.QLabel(self.centralWidget)
        self.lbl_objD.setGeometry(QtCore.QRect(725, 360, 30, 25))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_objD.setFont(font)
        self.lbl_objD.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255)\n"
"\n"
""))
        self.lbl_objD.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_objD.setObjectName(_fromUtf8("lbl_objD"))
        self.objD = QtGui.QLabel(self.centralWidget)
        self.objD.setGeometry(QtCore.QRect(700, 300, 80, 50))
        self.objD.setText(_fromUtf8(""))
        self.objD.setObjectName(_fromUtf8("objD"))
        self.lbl_objE = QtGui.QLabel(self.centralWidget)
        self.lbl_objE.setGeometry(QtCore.QRect(725, 450, 30, 25))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_objE.setFont(font)
        self.lbl_objE.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255)\n"
"\n"
""))
        self.lbl_objE.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_objE.setObjectName(_fromUtf8("lbl_objE"))
        self.objE = QtGui.QLabel(self.centralWidget)
        self.objE.setGeometry(QtCore.QRect(700, 395, 80, 50))
        self.objE.setText(_fromUtf8(""))
        self.objE.setObjectName(_fromUtf8("objE"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(660, 30, 4, 430))
        self.label.setStyleSheet(_fromUtf8("background-color: rgb(61, 61, 61)"))
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        BCARM.setCentralWidget(self.centralWidget)

        self.retranslateUi(BCARM)
        QtCore.QMetaObject.connectSlotsByName(BCARM)

    def retranslateUi(self, BCARM):
        BCARM.setWindowTitle(_translate("BCARM", "MainWindow", None))
        self.B.setText(_translate("BCARM", "B", None))
        self.A.setText(_translate("BCARM", "A", None))
        self.C.setText(_translate("BCARM", "C", None))
        self.E.setText(_translate("BCARM", "E", None))
        self.D.setText(_translate("BCARM", "D", None))
        self.F.setText(_translate("BCARM", "F", None))
        self.H.setText(_translate("BCARM", "H", None))
        self.G.setText(_translate("BCARM", "G", None))
        self.I.setText(_translate("BCARM", "I", None))
        self.lbl_objA.setText(_translate("BCARM", "A", None))
        self.lbl_objB.setText(_translate("BCARM", "B", None))
        self.lbl_objC.setText(_translate("BCARM", "C", None))
        self.lbl_objD.setText(_translate("BCARM", "D", None))
        self.lbl_objE.setText(_translate("BCARM", "E", None))

